### ISSUE TITLE
Feature: Copy to clipboard button for dApp URL

### ISSUE THREAD

**Issue by blockchainbuddha** [blockchainbuddha/one-click-dApp#20]
Generating the new DApp url should copy the link to the clipboard and display a small popup above the button letting the user know.

**Comment by malik97160** [comment]
I am working on it

**Comment by SubashAravindan** [comment]
I'll try this one

**Comment by RiotPharaoh** [comment]
Hi @blockchainbuddha, I'll do it for you until tomorrow, if you interested.

**Comment by jschiarizzi** [comment]
Yes, anyone can work on it, I will keep an eye open for the PR

**Comment by malik97160** [comment]
Sorry, I can't work on it.
